### ISSUE TITLE
ActionView::Template::Error (no implicit conversion of Symbol into Integer)

### ISSUE THREAD

**Issue by illuminated** [marcus-sacramento-redmine/redmine_portfolio_management#29]
After fresh install of the plugin (on Redmine 3.2.1), and setup (adding the custom fields), I get the following error when I open the Portfolio page:

```
Started GET "/portfolio_management" for 109.111.229.194 at 2016-05-04 11:19:09 +0200
Processing by PortfolioManagementController#index as HTML
  Current user: user@domain.com (id=5)
  Rendered plugins/redmine_portfolio_management/app/views/portfolio_management/index.html.erb within layouts/ba$
Completed 500 Internal Server Error in 17ms (ActiveRecord: 2.5ms)

ActionView::Template::Error (no implicit conversion of Symbol into Integer):
     5: <% end %>
     6: <h1><%= l(:portfolio_management_title) %></h1>
     7: <div id="projects-index">
     8:    <% RedminePortfolioManagement::Redmine::list_portfolio_values.each do |portfolio| %>
     9:    <h2><%=raw portfolio['value']%></h2>
    10:    <div class="datagrid">
    11:       <table class='table-autopage:10 table-autosort:2 table-stripeclass:alt sort5' id='<%=raw portfoli$
  plugins/redmine_portfolio_management/lib/redmine_portfolio_management/redmine.rb:121:in `[]'
  plugins/redmine_portfolio_management/lib/redmine_portfolio_management/redmine.rb:121:in `custom_field'
  plugins/redmine_portfolio_management/lib/redmine_portfolio_management/redmine.rb:19:in `portfolio_management_$
  plugins/redmine_portfolio_management/lib/redmine_portfolio_management/redmine.rb:31:in `list_portfolio_values'
  plugins/redmine_portfolio_management/app/views/portfolio_management/index.html.erb:8:in `_plugins_redmine_por$
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Similar thing happens when I open the plugin's setting page:

```
Started GET "/settings/plugin/redmine_portfolio_management" for 109.111.229.194 at 2016-05-04 11:19:37 +0200
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_portfolio_management"}
  Current user: user@domain.com (id=5)
  Rendered plugins/redmine_portfolio_management/app/views/settings/_redmine_portfolio_management_settings.html.$
  Rendered settings/plugin.html.erb within layouts/admin (3.3ms)
Completed 500 Internal Server Error in 10ms (ActiveRecord: 2.3ms)

ActionView::Template::Error (no implicit conversion of Symbol into Integer):
    3:       <tr>
    4:          <th align="left"><%= l(:portfolio_management_attribute) %></th>
    5:          <td width="450">
    6:             <%= select_tag 'settings[portfolio_management_attribute]', options_from_collection_for_selec$
    7:          </td>
    8:       </tr>
    9:       <tr>
  plugins/redmine_portfolio_management/app/views/settings/_redmine_portfolio_management_settings.html.erb:6:in $
  plugins/redmine_portfolio_management/app/views/settings/_redmine_portfolio_management_settings.html.erb:6:in $
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb___2032877796989764998_4$
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb___2032877796989764998_4721259569$
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by illuminated** [comment]
reinstall of redmine with al the plugins solved the issue.
